<?php

/**
 * PluginfzTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginfzTagTable extends Doctrine_Table
{

    protected $taggableModelsLoaded = false;

    /**
     * Returns an instance of this class.
     *
     * @return object PluginfzTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginfzTag');
    }

    /**
     * Method that returns array of tags (tagName => tagName) for autocomplete.
     * @return array
     * @author Grzegorz Śliwiński
     */
    public function getTagsForAutocomplete()
    {
        return $this->createQuery('t')->select('t.name as name')
                ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }

    /**
     * Method executes query on tags with given ids to increase their weight
     * @param array $tagIds
     */
    public function increaseTagsWeight(Array $tagIds)
    {

        if( count( $tagIds ) > 0 )
        {
            $this->createQuery('t')->update()
                    ->set('t.count', 't.count + 1')
                    ->whereIn('t.id', $tagIds)->execute();
        }
    }

    /**
     * Method executes query on tags with given ids to decrease their weight
     * @param array $tagIds
     */
    public function decreaseTagsWeight(Array $tagIds)
    {
        if( count( $tagIds ) > 0 )
        {
            $this->createQuery('t')->update()
                    ->set('t.count', 't.count - 1')
                    ->whereIn('t.id', $tagIds)
                    ->andWhere('t.count > 0')->execute();
        }
    }
}