<?php

/**
 * PluginfzTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginfzTagTable extends Doctrine_Table
{

    protected $taggableModelsLoaded = false;

    /**
     * Returns an instance of this class.
     *
     * @return object PluginfzTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginfzTag');
    }

    /**
     * Method that returns weight ordered query
     * @param integer $limit
     * @return Doctrine_Query
     * @author Grzegorz Śliwiński
     */
    public function getTagsForCloudQuery( $limit = 20)
    {
        //just to make sure, in case someone passes false, or anything
        if( !$limit or !is_numeric($limit) )
        {
            $limit = 20;
        }
        return $this->createQuery('t')
                ->where('t.id IN (SELECT t2.id FROM fzTag t2 WHERE t2.weight > 0 ORDER BY t2.weight DESC)')
                ->orderBy('RANDOM() ASC');

        $query = $this->createQuery('t')->where('t.weight > 0')->orderBy('t.weight DESC')->limit($limit);
        return $query;
    }

    /**
     * Method returns all possible weights values for getTagsWeightOrderedQuery method
     * @param integer $limit
     * @return Doctrine_Query
     * @author grzegorz Śliwiński
     */
    public function getWeightsForCloudQuery( $limit = null )
    {
        return $this->getTagsForCloudQuery($limit)->select('t.weight, COUNT(t.id) num')->groupBy('t.weight');
    }

    /**
     * This method returns sorted query, based on the passed array, that needs to consist of order & by keys
     * @param array $sortOptions
     * @return Doctrine_Query
     * @author Grzegorz Śliwiński
     */
    public function getListQuery( array $sortOptions = array() )
    {
        $query = $this->createQuery('t');

        $order = ' ASC';
        $by = 't.name';
        if(is_array($sortOptions) )
        {
            if( array_key_exists('order', $sortOptions ) && $sortOptions['order'] == 'desc' )
            {
                $order = ' DESC';
            }
            if( array_key_exists('by', $sortOptions ) && $sortOptions['by'] == 'weight' )
            {
                $by = 't.weight';
            }
        }

        return $query->orderBy($by.$order);
    }

    /**
     * Method that returns array of tags (tagName => tagName) for autocomplete.
     * @return array
     * @author Grzegorz Śliwiński
     */
    public function getTagsForAutocomplete()
    {
        return $this->createQuery('t')->select('t.name as name')
                ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }

    /**
     * Method executes query on tags with given ids to increase their weight
     * @param array $tagIds
     */
    public function increaseTagsWeight(Array $tagIds)
    {

        if( count( $tagIds ) > 0 )
        {
            $this->createQuery('t')->update()
                    ->set('t.weight', 't.weight + 1')
                    ->whereIn('t.id', $tagIds)->execute();
        }
    }

    /**
     * Method executes query on tags with given ids to decrease their weight
     * @param array $tagIds
     */
    public function decreaseTagsWeight(Array $tagIds)
    {
        if( count( $tagIds ) > 0 )
        {
            $this->createQuery('t')->update()
                    ->set('t.weight', 't.weight - 1')
                    ->whereIn('t.id', $tagIds)
                    ->andWhere('t.weight > 0')->execute();
        }
    }
}