all:

  fzTagPlugin:

    fcbkcomplete:           # options to pass to the jQuery.fcbkcomplete plugin
                            # see http://www.emposha.com/javascript/fcbkcomplete.html

      newel:          true  # show typed text like a element
      filter_case:    false # case sensitive filter
      filter_hide:    false # show/hide filtered items
      maxshownitems:  30    # maximum numbers that will be shown at dropdown list (less better performance)
      maxitems:       10    # maximum item that can be added to the list
      firstselected:  false # automaticly select first element from dropdown
    list_max_tags:    10    # number of tags shown on a list
    list_sort_default:      # default list order
      by:             name
      order:          asc